<?php


   define("DB_SERVER", "localhost");
   define("DB_USER", "root");
   define("DB_PASS", "");
   define("DB_NAME", "bisbuilder");

   define("MAX_ZONE_ID", 107);   // 77=original 129=kunark  179=luclin
   define("MAX_NPC_ID", 129098);


   $simpleClassIndexes = Array(
      "1"=>  (object) Array("name"=> "Warrior", "abbrv"=> "war"),
      "2"=>  (object) Array("name"=> "Cleric", "abbrv"=> "clr"),
      "3"=>  (object) Array("name"=> "Paladin", "abbrv"=> "pal"),
      "4"=>  (object) Array("name"=> "Ranger", "abbrv"=> "rng"),
      "5"=>  (object) Array("name"=> "Shadowknight", "abbrv"=> "shd"),
      "6"=>  (object) Array("name"=> "Druid", "abbrv"=> "dru"),
      "7"=>  (object) Array("name"=> "Monk", "abbrv"=> "mnk"),
      "8"=>  (object) Array("name"=> "Bard", "abbrv"=> "brd"),
      "9"=>  (object) Array("name"=> "Rogue", "abbrv"=> "rog"),
      "10"=> (object) Array("name"=> "Shaman", "abbrv"=> "shm"),
      "11"=> (object) Array("name"=> "Necromancer", "abbrv"=> "nec"),
      "12"=> (object) Array("name"=> "Wizard", "abbrv"=> "wiz"),
      "13"=> (object) Array("name"=> "Magician", "abbrv"=> "mag"),
      "14"=> (object) Array("name"=> "Enchanter", "abbrv"=> "enc"),
      "15"=> (object) Array("name"=> "Beastlord", "abbrv"=> "bst"),
      "16"=> (object) Array("name"=> "Berserker", "abbrv"=> "ber"),
   );

   //$simpleClassIndexes = (object) $simpleClassIndexes;

   $zones = Array(
      "154"=> (object) Array("short_name"=> "acrylia", "long_name"=> "The Acrylia Caverns"),
      "71"=> (object) Array("short_name"=> "airplane", "long_name"=> "The Plane of Sky"),
      "55"=> (object) Array("short_name"=> "akanon", "long_name"=> "Ak'Anon"),
      "179"=> (object) Array("short_name"=> "akheva", "long_name"=> "The Akheva Ruins"),
      "77"=> (object) Array("short_name"=> "arena", "long_name"=> "The Arena"),
      "180"=> (object) Array("short_name"=> "arena2", "long_name"=> "The Arena Two"),
      "53"=> (object) Array("short_name"=> "aviak", "long_name"=> "Aviak Village"),
      "36"=> (object) Array("short_name"=> "befallen", "long_name"=> "Befallen"),
      "16"=> (object) Array("short_name"=> "beholder", "long_name"=> "Gorge of King Xorbb"),
      "17"=> (object) Array("short_name"=> "blackburrow", "long_name"=> "Blackburrow"),
      "209"=> (object) Array("short_name"=> "bothunder", "long_name"=> "Bastion of Thunder"),
      "87"=> (object) Array("short_name"=> "burningwood", "long_name"=> "The Burning Wood"),
      "68"=> (object) Array("short_name"=> "butcher", "long_name"=> "Butcherblock Mountains"),
      "106"=> (object) Array("short_name"=> "cabeast", "long_name"=> "Cabilis East"),
      "82"=> (object) Array("short_name"=> "cabwest", "long_name"=> "Cabilis West"),
      "70"=> (object) Array("short_name"=> "cauldron", "long_name"=> "Dagnor's Cauldron"),
      "48"=> (object) Array("short_name"=> "cazicthule", "long_name"=> "Accursed Temple of CazicThule"),
      "105"=> (object) Array("short_name"=> "charasis", "long_name"=> "The Howling Stones"),
      "103"=> (object) Array("short_name"=> "chardok", "long_name"=> "Chardok"),
      "90"=> (object) Array("short_name"=> "citymist", "long_name"=> "The City of Mist"),
      "190"=> (object) Array("short_name"=> "clz", "long_name"=> "Loading"),
      "117"=> (object) Array("short_name"=> "cobaltscar", "long_name"=> "Cobaltscar"),
      "200"=> (object) Array("short_name"=> "codecay", "long_name"=> "The Crypt of Decay"),
      "21"=> (object) Array("short_name"=> "commons", "long_name"=> "West Commonlands"),
      "58"=> (object) Array("short_name"=> "crushbone", "long_name"=> "Crushbone"),
      "121"=> (object) Array("short_name"=> "crystal", "long_name"=> "The Crystal Caverns"),
      "26"=> (object) Array("short_name"=> "cshome", "long_name"=> "Sunset Home"),
      "104"=> (object) Array("short_name"=> "dalnir", "long_name"=> "The Crypt of Dalnir"),
      "174"=> (object) Array("short_name"=> "dawnshroud", "long_name"=> "The Dawnshroud Peaks"),
      "86"=> (object) Array("short_name"=> "dreadlands", "long_name"=> "The Dreadlands"),
      "81"=> (object) Array("short_name"=> "droga", "long_name"=> "The Temple of Droga"),
      "15"=> (object) Array("short_name"=> "eastkarana", "long_name"=> "Eastern Plains of Karana"),
      "116"=> (object) Array("short_name"=> "eastwastes", "long_name"=> "Eastern Wastes"),
      "153"=> (object) Array("short_name"=> "echo", "long_name"=> "The Echo Caverns"),
      "22"=> (object) Array("short_name"=> "ecommons", "long_name"=> "East Commonlands"),
      "94"=> (object) Array("short_name"=> "emeraldjungle", "long_name"=> "The Emerald Jungle"),
      "24"=> (object) Array("short_name"=> "erudnext", "long_name"=> "Erudin"),
      "23"=> (object) Array("short_name"=> "erudnint", "long_name"=> "The Erudin Palace"),
      "98"=> (object) Array("short_name"=> "erudsxing", "long_name"=> "Erud's Crossing"),
      "130"=> (object) Array("short_name"=> "erudsxing2", "long_name"=> "Marauders Mire"),
      "30"=> (object) Array("short_name"=> "everfrost", "long_name"=> "Everfrost Peaks"),
      "72"=> (object) Array("short_name"=> "fearplane", "long_name"=> "The Plane of Fear"),
      "47"=> (object) Array("short_name"=> "feerrott", "long_name"=> "The Feerrott"),
      "61"=> (object) Array("short_name"=> "felwithea", "long_name"=> "Northern Felwithe"),
      "62"=> (object) Array("short_name"=> "felwitheb", "long_name"=> "Southern Felwithe"),
      "78"=> (object) Array("short_name"=> "fieldofbone", "long_name"=> "The Field of Bone"),
      "84"=> (object) Array("short_name"=> "firiona", "long_name"=> "Firiona Vie"),
      "10"=> (object) Array("short_name"=> "freporte", "long_name"=> "East Freeport"),
      "8"=> (object) Array("short_name"=> "freportn", "long_name"=> "North Freeport"),
      "9"=> (object) Array("short_name"=> "freportw", "long_name"=> "West Freeport"),
      "92"=> (object) Array("short_name"=> "frontiermtns", "long_name"=> "Frontier Mountains"),
      "111"=> (object) Array("short_name"=> "frozenshadow", "long_name"=> "The Tower of Frozen Shadow"),
      "157"=> (object) Array("short_name"=> "fungusgrove", "long_name"=> "The Fungus Grove"),
      "54"=> (object) Array("short_name"=> "gfaydark", "long_name"=> "The Greater Faydark"),
      "118"=> (object) Array("short_name"=> "greatdivide", "long_name"=> "The Great Divide"),
      "163"=> (object) Array("short_name"=> "griegsend", "long_name"=> "Grieg's End"),
      "167"=> (object) Array("short_name"=> "grimling", "long_name"=> "Grimling Forest"),
      "52"=> (object) Array("short_name"=> "grobb", "long_name"=> "Grobb"),
      "127"=> (object) Array("short_name"=> "growthplane", "long_name"=> "The Plane of Growth"),
      "66"=> (object) Array("short_name"=> "gukbottom", "long_name"=> "The Ruins of Old Guk"),
      "65"=> (object) Array("short_name"=> "guktop", "long_name"=> "The City of Guk"),
      "29"=> (object) Array("short_name"=> "halas", "long_name"=> "Halas"),
      "76"=> (object) Array("short_name"=> "hateplane", "long_name"=> "Plane of Hate"),
      "6"=> (object) Array("short_name"=> "highkeep", "long_name"=> "High Keep"),
      "5"=> (object) Array("short_name"=> "highpass", "long_name"=> "Highpass Hold"),
      "211"=> (object) Array("short_name"=> "hohonora", "long_name"=> "The Halls of Honor"),
      "220"=> (object) Array("short_name"=> "hohonorb", "long_name"=> "The Temple of Marr"),
      "39"=> (object) Array("short_name"=> "hole", "long_name"=> "The Hole"),
      "166"=> (object) Array("short_name"=> "hollowshade", "long_name"=> "Hollowshade Moor"),
      "110"=> (object) Array("short_name"=> "iceclad", "long_name"=> "The Iceclad Ocean"),
      "46"=> (object) Array("short_name"=> "innothule", "long_name"=> "Innothule Swamp"),
      "181"=> (object) Array("short_name"=> "jaggedpine", "long_name"=> "The Jaggedpine Forest"),
      "113"=> (object) Array("short_name"=> "kael", "long_name"=> "Kael Drakkel"),
      "88"=> (object) Array("short_name"=> "kaesora", "long_name"=> "Kaesora"),
      "60"=> (object) Array("short_name"=> "kaladima", "long_name"=> "South Kaladim"),
      "67"=> (object) Array("short_name"=> "kaladimb", "long_name"=> "North Kaladim"),
      "102"=> (object) Array("short_name"=> "karnor", "long_name"=> "Karnor's Castle"),
      "160"=> (object) Array("short_name"=> "katta", "long_name"=> "Katta Castellum"),
      "64"=> (object) Array("short_name"=> "kedge", "long_name"=> "Kedge Keep"),
      "74"=> (object) Array("short_name"=> "kerraridge", "long_name"=> "Kerra Isle"),
      "20"=> (object) Array("short_name"=> "kithicor", "long_name"=> "Kithicor Forest"),
      "97"=> (object) Array("short_name"=> "kurn", "long_name"=> "Kurn's Tower"),
      "85"=> (object) Array("short_name"=> "lakeofillomen", "long_name"=> "Lake of Ill Omen"),
      "51"=> (object) Array("short_name"=> "lakerathe", "long_name"=> "Lake Rathetear"),
      "27"=> (object) Array("short_name"=> "lavastorm", "long_name"=> "The Lavastorm Mountains"),
      "169"=> (object) Array("short_name"=> "letalis", "long_name"=> "Mons Letalis"),
      "57"=> (object) Array("short_name"=> "lfaydark", "long_name"=> "The Lesser Faydark"),
      "184"=> (object) Array("short_name"=> "load", "long_name"=> "Loading Zone"),
      "185"=> (object) Array("short_name"=> "load2", "long_name"=> "New Loading Zone"),
      "173"=> (object) Array("short_name"=> "maiden", "long_name"=> "The Maiden's Eye"),
      "126"=> (object) Array("short_name"=> "mischiefplane", "long_name"=> "The Plane of Mischief"),
      "59"=> (object) Array("short_name"=> "mistmoore", "long_name"=> "The Castle of Mistmoore"),
      "33"=> (object) Array("short_name"=> "misty", "long_name"=> "Misty Thicket"),
      "168"=> (object) Array("short_name"=> "mseru", "long_name"=> "Marus Seru"),
      "44"=> (object) Array("short_name"=> "najena", "long_name"=> "Najena"),
      "123"=> (object) Array("short_name"=> "necropolis", "long_name"=> "Dragon Necropolis"),
      "28"=> (object) Array("short_name"=> "nektropos", "long_name"=> "Nektropos"),
      "40"=> (object) Array("short_name"=> "neriaka", "long_name"=> "Neriak - Foreign Quarter"),
      "41"=> (object) Array("short_name"=> "neriakb", "long_name"=> "Neriak - Commons"),
      "42"=> (object) Array("short_name"=> "neriakc", "long_name"=> "Neriak - 3rd Gate"),
      "43"=> (object) Array("short_name"=> "neriakd", "long_name"=> "Neriak Palace"),
      "161"=> (object) Array("short_name"=> "netherbian", "long_name"=> "Netherbian Lair"),
      "152"=> (object) Array("short_name"=> "nexus", "long_name"=> "Nexus"),
      "221"=> (object) Array("short_name"=> "nightmareb", "long_name"=> "The Lair of Terris Thule"),
      "13"=> (object) Array("short_name"=> "northkarana", "long_name"=> "The Northern Plains of Karana"),
      "34"=> (object) Array("short_name"=> "nro", "long_name"=> "Northern Desert of Ro"),
      "107"=> (object) Array("short_name"=> "nurga", "long_name"=> "The Mines of Nurga"),
      "37"=> (object) Array("short_name"=> "oasis", "long_name"=> "Oasis of Marr"),
      "49"=> (object) Array("short_name"=> "oggok", "long_name"=> "Oggok"),
      "69"=> (object) Array("short_name"=> "oot", "long_name"=> "Ocean of Tears"),
      "93"=> (object) Array("short_name"=> "overthere", "long_name"=> "The Overthere"),
      "75"=> (object) Array("short_name"=> "paineel", "long_name"=> "Paineel"),
      "156"=> (object) Array("short_name"=> "paludal", "long_name"=> "The Paludal Caverns"),
      "18"=> (object) Array("short_name"=> "paw", "long_name"=> "The Lair of the Splitpaw"),
      "73"=> (object) Array("short_name"=> "permafrost", "long_name"=> "The Permafrost Caverns"),
      "215"=> (object) Array("short_name"=> "poair", "long_name"=> "The Plane of Air"),
      "205"=> (object) Array("short_name"=> "podisease", "long_name"=> "The Plane of Disease"),
      "218"=> (object) Array("short_name"=> "poeartha", "long_name"=> "The Plane of Earth"),
      "222"=> (object) Array("short_name"=> "poearthb", "long_name"=> "The Plane of Earth"),
      "217"=> (object) Array("short_name"=> "pofire", "long_name"=> "The Plane of Fire"),
      "206"=> (object) Array("short_name"=> "poinnovation", "long_name"=> "The Plane of Innovation"),
      "201"=> (object) Array("short_name"=> "pojustice", "long_name"=> "The Plane of Justice"),
      "202"=> (object) Array("short_name"=> "poknowledge", "long_name"=> "The Plane of Knowledge"),
      "204"=> (object) Array("short_name"=> "ponightmare", "long_name"=> "The Plane of Nightmares"),
      "210"=> (object) Array("short_name"=> "postorms", "long_name"=> "The Plane of Storms"),
      "214"=> (object) Array("short_name"=> "potactics", "long_name"=> "Drunder, the Fortress of Zek"),
      "219"=> (object) Array("short_name"=> "potimea", "long_name"=> "The Plane of Time"),
      "223"=> (object) Array("short_name"=> "potimeb", "long_name"=> "The Plane of Time"),
      "207"=> (object) Array("short_name"=> "potorment", "long_name"=> "Torment, the Plane of Pain"),
      "203"=> (object) Array("short_name"=> "potranquility", "long_name"=> "The Plane of Tranquility"),
      "208"=> (object) Array("short_name"=> "povalor", "long_name"=> "The Plane of Valor"),
      "213"=> (object) Array("short_name"=> "powar", "long_name"=> "Plane of War"),
      "216"=> (object) Array("short_name"=> "powater", "long_name"=> "The Plane of Water"),
      "45"=> (object) Array("short_name"=> "qcat", "long_name"=> "Qeynos Aqueducts"),
      "12"=> (object) Array("short_name"=> "qey2hh1", "long_name"=> "The Western Plains of Karana"),
      "1"=> (object) Array("short_name"=> "qeynos", "long_name"=> "South Qeynos"),
      "2"=> (object) Array("short_name"=> "qeynos2", "long_name"=> "North Qeynos"),
      "4"=> (object) Array("short_name"=> "qeytoqrg", "long_name"=> "The Qeynos Hills"),
      "3"=> (object) Array("short_name"=> "qrg", "long_name"=> "The Surefall Glade"),
      "50"=> (object) Array("short_name"=> "rathemtn", "long_name"=> "The Rathe Mountains"),
      "19"=> (object) Array("short_name"=> "rivervale", "long_name"=> "Rivervale"),
      "11"=> (object) Array("short_name"=> "runnyeye", "long_name"=> "The Liberated Citadel of Runnyeye"),
      "175"=> (object) Array("short_name"=> "scarlet", "long_name"=> "The Scarlet Desert"),
      "89"=> (object) Array("short_name"=> "sebilis", "long_name"=> "The Ruins of Sebilis"),
      "165"=> (object) Array("short_name"=> "shadeweaver", "long_name"=> "Shadeweaver's Thicket"),
      "150"=> (object) Array("short_name"=> "shadowhaven", "long_name"=> "Shadow Haven"),
      "155"=> (object) Array("short_name"=> "sharvahl", "long_name"=> "The City of Shar Vahl"),
      "125"=> (object) Array("short_name"=> "sirens", "long_name"=> "Siren's Grotto"),
      "91"=> (object) Array("short_name"=> "skyfire", "long_name"=> "The Skyfire Mountains"),
      "114"=> (object) Array("short_name"=> "skyshrine", "long_name"=> "Skyshrine"),
      "128"=> (object) Array("short_name"=> "sleeper", "long_name"=> "The Sleeper's Tomb"),
      "31"=> (object) Array("short_name"=> "soldunga", "long_name"=> "Solusek's Eye"),
      "32"=> (object) Array("short_name"=> "soldungb", "long_name"=> "Nagafen's Lair"),
      "212"=> (object) Array("short_name"=> "solrotower", "long_name"=> "The Tower of Solusek Ro"),
      "80"=> (object) Array("short_name"=> "soltemple", "long_name"=> "The Temple of Solusek Ro"),
      "14"=> (object) Array("short_name"=> "southkarana", "long_name"=> "The Southern Plains of Karana"),
      "35"=> (object) Array("short_name"=> "sro", "long_name"=> "Southern Desert of Ro"),
      "159"=> (object) Array("short_name"=> "sseru", "long_name"=> "Sanctus Seru"),
      "162"=> (object) Array("short_name"=> "ssratemple", "long_name"=> "Ssraeshza Temple"),
      "56"=> (object) Array("short_name"=> "steamfont", "long_name"=> "Steamfont Mountains"),
      "100"=> (object) Array("short_name"=> "stonebrunt", "long_name"=> "The Stonebrunt Mountains"),
      "83"=> (object) Array("short_name"=> "swampofnohope", "long_name"=> "The Swamp of No Hope"),
      "124"=> (object) Array("short_name"=> "templeveeshan", "long_name"=> "The Temple of Veeshan"),
      "172"=> (object) Array("short_name"=> "tenebrous", "long_name"=> "The Tenebrous Mountains"),
      "164"=> (object) Array("short_name"=> "thedeep", "long_name"=> "The Deep"),
      "171"=> (object) Array("short_name"=> "thegrey", "long_name"=> "The Grey"),
      "115"=> (object) Array("short_name"=> "thurgadina", "long_name"=> "The City of Thurgadin"),
      "129"=> (object) Array("short_name"=> "thurgadinb", "long_name"=> "Icewell Keep"),
      "96"=> (object) Array("short_name"=> "timorous", "long_name"=> "Timorous Deep"),
      "38"=> (object) Array("short_name"=> "tox", "long_name"=> "Toxxulia Forest"),
      "95"=> (object) Array("short_name"=> "trakanon", "long_name"=> "Trakanon's Teeth"),
      "183"=> (object) Array("short_name"=> "tutorial", "long_name"=> "EverQuest Tutorial"),
      "170"=> (object) Array("short_name"=> "twilight", "long_name"=> "The Twilight Sea"),
      "176"=> (object) Array("short_name"=> "umbral", "long_name"=> "The Umbral Plains"),
      "63"=> (object) Array("short_name"=> "unrest", "long_name"=> "The Estate of Unrest"),
      "108"=> (object) Array("short_name"=> "veeshan", "long_name"=> "Veeshan's Peak"),
      "109"=> (object) Array("short_name"=> "veksar", "long_name"=> "Veksar"),
      "112"=> (object) Array("short_name"=> "velketor", "long_name"=> "Velketor's Labyrinth"),
      "158"=> (object) Array("short_name"=> "vexthal", "long_name"=> "Vex Thal"),
      "119"=> (object) Array("short_name"=> "wakening", "long_name"=> "The Wakening Land"),
      "101"=> (object) Array("short_name"=> "warrens", "long_name"=> "The Warrens"),
      "79"=> (object) Array("short_name"=> "warslikswood", "long_name"=> "The Warsliks Woods"),
      "120"=> (object) Array("short_name"=> "westwastes", "long_name"=> "The Western Wastes"),
      "25"=> (object) Array("short_name"=> "nektulos", "long_name"=> "The Nektulos Forest"),
      "151"=> (object) Array("short_name"=> "bazaar", "long_name"=> "The Bazaar"),
      "408"=> (object) Array("short_name"=> "commonlands", "long_name"=> "The Commonlands"),

      // extra zones / revamped zones
      "393"=> (object) Array("short_name"=> "southro", "long_name"=> "South Ro")
   );


?>